### ISSUE TITLE
Install cmake files

### ISSUE THREAD

**Issue by WorldSEnder** [smtrat/carl#11]
Currently in cmake/export.cmake you only configure the cmake config files. But I think that they are never getting installed:

install(FILES ${CMAKE_CURRENT_BINARY_DIR}/carlConfig.cmake 
		DESTINATION ${CMAKE_INSTALL_DIR} )

**Comment by nafur** [comment]
That's right, I just didn't manage to check what exactly was to be done and to fix it yet. Is this the actual install command missing?

**Comment by WorldSEnder** [comment]
yes, that should install the config files. I'm not experienced with it myself, maybe you have to install carlTargets.cmake aswell

**Comment by nafur** [comment]
Okay, so does 3c7e38b6 do the job for you?
(In case you test that with the arch package: this will use the last tag, not the current HEAD...)

**Comment by WorldSEnder** [comment]
Yes, that works. Can you also update to this revision on the AUR?

**Comment by WorldSEnder** [comment]
CMAKE_INSTALL_DIR should be lower case, i.e. here: https://github.com/miloyip/rapidjson/blob/master/CMakeLists.txt#L116

One thing, since 37ca676ab32388c33a70b5e23c48b935a96be305 you use CMAKE_INSTALL_LIBDIR. CMake deduces this to lib64 when I build the package which is normally correct on my system. But when using a package manager, the files should be installed to lib. The solution would be to add -DCMAKE_INSTALL_LIBDIR=lib in the PKGBUILD when calling cmake. See also https://bbs.archlinux.org/viewtopic.php?id=195142

**Comment by WorldSEnder** [comment]
hm, since 37ca676ab32388c33a70b5e23c48b935a96be305 the install process is a bit messed up. I'll try to clean it up and submit a pull request

**Comment by WorldSEnder** [comment]
#13

**Comment by nafur** [comment]
Merged #13. So does this work for you now?

**Comment by WorldSEnder** [comment]
Works great as far as I can see

**Comment by WorldSEnder** [comment]
I just realized an oversight of mine in commit 6f3133099b80cd6c95f02d9d7b677ee970dad3bd. You should reroll my changes to the file `carlConfig.cmake.in`.

I initially changed lib_carl to carl to test linking with just `-lcarl`. This works, but with the change, transitive dependencies are forgotten about. To be clear it should be

`set(carl_LIBRARIES lib_carl)` to refer to the target

**Comment by nafur** [comment]
I assume I will refactor this a bit, but not within the next few weeks. For now, I just merged this.
