### ISSUE TITLE
FactorizedPolynomial.tpp: returns value for void function

### ISSUE THREAD

**Issue by kleinj** [smtrat/carl#18]
In the implementation of `substituteIn` for `FactorizedPolynomial<P>`
https://github.com/smtrat/carl/blob/a1b2487c8a00749728783a79c54e85e5e96a5f07/src/carl/core/FactorizedPolynomial.h#L577-L580

the function returns a value, but has `void` return type:
https://github.com/smtrat/carl/blob/e905520de4512a4ba6d9b1396419ed50a46d0b0e/src/carl/core/FactorizedPolynomial.tpp#L723-L729

Looks like the logic does not match the interface, as well.

While the current release versions of GCC (7.x) compile this, for a GCC of the current development branch (8) this results in an error message.

**Comment by nafur** [comment]
Besides the compilation issue, this does not implement an in-place substitution.
@volkm Could you take a look at this?

**Comment by nafur** [comment]
Some progress report: As GCC8 slowly transitions into production (Arch Linux now ships it) we also have this issue now and @volkm promised to fix it soonish. Indeed this highlighted a much bigger underlying problem with the substitute method that we intend to fix at the same time.

**Comment by kleinj** [comment]
I guess replacing the
```return res;```
with
```*this = std::move(res);```
and adding a move constructor for FactorizedPolynomial (correctly handling the cache reference counting) would be the easiest fix?

**Comment by nafur** [comment]
Thanks to @volkm , this issue should be resolved now.

**Comment by volkm** [comment]
Just for future reference:
I removed the in place substitution for `FactorizedPolynomial` and only kept the one returning a substituted copy. We cannot implement a fully in place substitution as the factors of a `FactorizedPolynomial` are stored uniquely in a cache. Substituting in place could potentially change a factor which might be used in other `FactorizedPolynomials` as well and therefore invalidate the factorizations of other polynomials.
