### ISSUE TITLE
Auto installing ginac 

### ISSUE THREAD

**Issue by sjunges** [smtrat/carl#2]
Installing ginac via carl does not seem to be working.

Details: Ubuntu 16-10, cmake options: USE_GINAC = 1.

> 
> Scanning dependencies of target ginac
> [  1%] Performing update step for 'googletest'
> [  2%] Creating directories for 'ginac'
> [  8%] Built target EIGEN3_REPO
> [  8%] Performing configure step for 'googletest'
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/sebastian/i2/carl/build/resources/src/googletest-build
> [  9%] Performing download step (git clone) for 'ginac'
> [ 10%] Performing build step for 'googletest'
> Cloning into 'ginac'...
> [ 50%] Built target gtest
> [100%] Built target gtest_main
> [ 12%] No install step for 'googletest'
> [ 13%] Completed 'googletest'
> [ 15%] Built target googletest
> Note: checking out 'release_1-6-7'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
>   git checkout -b <new-branch-name>
> 
> HEAD is now at 065600d... Finalize 1.6.7 release.
> [ 16%] No patch step for 'ginac'
> [ 16%] Performing update step for 'ginac'
> [ 18%] Performing configure step for 'ginac'
> autoreconf: 'configure.ac' or 'configure.in' is required
> CMakeFiles/ginac.dir/build.make:105: recipe for target 'resources/src/ginac-stamp/ginac-configure' failed
> make[2]: *** [resources/src/ginac-stamp/ginac-configure] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ginac.dir/all' failed
> make[1]: *** [CMakeFiles/ginac.dir/all] Error 2
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2
> ➜  build git:(master) make -j8
> [  6%] Built target EIGEN3_REPO
> [  6%] Performing update step for 'ginac'
> [  7%] Performing update step for 'googletest'
> [  7%] Performing configure step for 'googletest'
> [  8%] Performing configure step for 'ginac'
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/sebastian/i2/carl/build/resources/src/googletest-build
> [  9%] Performing build step for 'googletest'
> [ 50%] Built target gtest
> [100%] Built target gtest_main
> [ 10%] No install step for 'googletest'
> [ 12%] Completed 'googletest'
> [ 14%] Built target googletest
> autoreconf: 'configure.ac' or 'configure.in' is required
> CMakeFiles/ginac.dir/build.make:105: recipe for target 'resources/src/ginac-stamp/ginac-configure' failed
> make[2]: *** [resources/src/ginac-stamp/ginac-configure] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ginac.dir/all' failed
> make[1]: *** [CMakeFiles/ginac.dir/all] Error 2
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2
>

**Comment by smtrat** [comment]
Hm, the paths for an out-of-source build were incorrect.
Fixed with 9d7481f
