### ISSUE TITLE
Windows10 installation help

### ISSUE THREAD

**Issue by Nervous-** [smtrat/carl#20]
hey, guys, i want to use carl lib to do something, and i just read the documents in your website, i,m using windows10 64 bit, and visual studio 2015, when i use cmake(GUI) to generate the sln project, i got some problems, i known these problems are too easy to address for an expert C++er, unfortunately, i,m not, so i needy your help. the problems list as follows:
1.when i use cmake to generate the sln project and use VS2015 to compile them , i just run the ALL_BUILD project ,and the VS2015 will downloading boost and something else, but i was already installed the boost lib in my C:\Program Files\boost\,why can't the cmake find it???
2.do i need to run ALL_BUILD project?i just want to use carl as a lib or dll, ALL_BUILD just build something i don't need,which is the right project i shoud compile? 
3.do you guys update your website the windows installation guide? could you please show me a more clear installation guide on windows10 64bit and VS2015??
waiting for your help!
best.

----------------------------------------------------------------------------------------------------
 more clearly，i'm using cmake 3.12（i‘ve tried 3.11，it still doesn't work）,when i use cmake to build the project, it throws the errors like this:
![image](https://user-images.githubusercontent.com/7833870/42412925-58bf07e0-8248-11e8-81b0-de1198ca8ac7.png)
i've serached the solution about this problem, and most of them think the reason is the cmake version is not compatiable with the boost version, but i think it's not, so could you please address this problem? is this the cmake codes' problem?
waiting for your help!!!
best!

---------------------------------------------------------------------------------------------------------------
additionally， when i compile the lib_carl using VS2015, errors occurs just like this:
![image](https://user-images.githubusercontent.com/7833870/42459760-ef59b0ce-83ce-11e8-91b1-a646c67f4d59.png)
it shows that 'cp' is not recognized as an internal or external command, please show me a windows installation guide please!

**Comment by nafur** [comment]
First of, our documentation is not up to date, in particular not when it comes to setup.
Unfortunately, none of the people that actively work on or use carl (or smtrat) uses Windows as their primary operating system. As such, there is no proper support for Windows. I started doing CI with carl on appveyor at some point, but never really finished it.

That being said: we do not expect carl/smtrat to build on Windows without problems, neither the build system nor the code itself. In particular, the build system support may be highly specific to appveyor as of now. If you are motivated to improve the situation, I'm very happy to accept patches and answer any questions.

You can see the latest status of carl on windows at https://ci.appveyor.com/project/smtrat/carl. As you can see, the build somewhat works, but not completely.

In general, see https://github.com/smtrat/carl/blob/master/.appveyor.yml and https://github.com/smtrat/carl/blob/master/.ci/setup_appveyor.ps1 for what we do.
On appveyor, boost is preinstalled and we use that one. GMP and Eigen are installed via external projects and should work (we have a separate one for GMP as we have to use MPIR). All other dependencies (which are optional and disabled by default) may or may not work, probably the latter for some minor technical details in the external projects, though I never checked...

I would expect that we only need few easy changes to make the build system work and only a few - though maybe more subtle fixes - to the code itself, as we have fairly high-level code. However, the VS STL behaved somewhat differently in unexpected places when I worked on that. Having no proper Windows at hand, debugging proved extremely painful for me. It might be way easier for you.

**Comment by nafur** [comment]
And Matthias suggested something else: If you don't care about using VisualStudio or alike, you can use the Linux Subsystem (on Windows 10) to run carl/smtrat.

**Comment by Nervous-** [comment]
thank you for your helpful response，i'm into linux now and everything works well.thank you again

**Comment by Nervous-** [comment]
Hey，guys，i just find an exciting way to coding linux codes in windows platform, it's quite easy, all the things i need to do is to install ssh related softwares in linux and the IDE(i'm using CLion), in windows platform , i just intsall mobaxterm and connect the linux server, so, finally i just start the clion in mobaxterm's terminal and the CLion's GUI will appears in my windows platform, and there is no need to config anything about file synchronization，no need to do anything about the IDE's environment,  cause  all the files you are reading and writing are from linux server, i think this is the most easy way to realize remote debugging。

**Comment by nafur** [comment]
As this issue seems to be resolved...
