### ISSUE TITLE
configuration problem 

### ISSUE THREAD

**Issue by Nervous-** [smtrat/carl#26]
-- The CXX compiler identification is GNU 8.2.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
fatal: 不是一个 git 仓库（或者任何父目录）：.git
-- Could not parse version from git, using default 19.01
-- Version: carl 19.01
-- Using g++ 8.2.0
-- CXX Flags:  -Wunknown-pragmas -std=c++17 -pthread -fmax-errors=5 -fdiagnostics-color=auto
-- CXX Debug Flags: -g -O1
-- CXX Release Flags: -O3 -DNDEBUG -O3
-- Build type: RELEASE
-- cotire is disabled
-- GMP / GMPXX 6.1.2 was found at /usr/include/x86_64-linux-gnu and /usr/lib/x86_64-linux-gnu/libgmp.so
-- Found Boost 1.70.0 at /usr/local/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET COMPONENTS system;program_options;regex;unit_test_framework;timer;chrono
-- Found boost_headers 1.70.0 at /usr/local/lib/cmake/boost_headers-1.70.0
-- Found boost_system 1.70.0 at /usr/local/lib/cmake/boost_system-1.70.0
-- No suitable boost_system variant has been identified!
--   libboost_system.so.1.70.0 (shared, BUILD_SHARED_LIBS not ON, set Boost_USE_STATIC_LIBS=OFF to override)
--   libboost_system.a (static, Boost_USE_STATIC_LIBS=OFF)
-- Found boost_program_options 1.70.0 at /usr/local/lib/cmake/boost_program_options-1.70.0
-- No suitable boost_program_options variant has been identified!
--   libboost_program_options.so.1.70.0 (shared, BUILD_SHARED_LIBS not ON, set Boost_USE_STATIC_LIBS=OFF to override)
--   libboost_program_options.a (static, Boost_USE_STATIC_LIBS=OFF)
-- Found boost_regex 1.70.0 at /usr/local/lib/cmake/boost_regex-1.70.0
-- No suitable boost_regex variant has been identified!
--   libboost_regex.so.1.70.0 (shared, BUILD_SHARED_LIBS not ON, set Boost_USE_STATIC_LIBS=OFF to override)
--   libboost_regex.a (static, Boost_USE_STATIC_LIBS=OFF)
-- Found boost_unit_test_framework 1.70.0 at /usr/local/lib/cmake/boost_unit_test_framework-1.70.0
-- No suitable boost_unit_test_framework variant has been identified!
--   libboost_unit_test_framework.so.1.70.0 (shared, BUILD_SHARED_LIBS not ON, set Boost_USE_STATIC_LIBS=OFF to override)
--   libboost_unit_test_framework.a (static, Boost_USE_STATIC_LIBS=OFF)
-- Found boost_timer 1.70.0 at /usr/local/lib/cmake/boost_timer-1.70.0
-- No suitable boost_timer variant has been identified!
--   libboost_timer.so.1.70.0 (shared, BUILD_SHARED_LIBS not ON, set Boost_USE_STATIC_LIBS=OFF to override)
--   libboost_timer.a (static, Boost_USE_STATIC_LIBS=OFF)
-- Found boost_chrono 1.70.0 at /usr/local/lib/cmake/boost_chrono-1.70.0
-- No suitable boost_chrono variant has been identified!
--   libboost_chrono.so.1.70.0 (shared, BUILD_SHARED_LIBS not ON, set Boost_USE_STATIC_LIBS=OFF to override)
--   libboost_chrono.a (static, Boost_USE_STATIC_LIBS=OFF)
-- Boost 1.65.1 found.
-- Found Boost components:
   system;program_options;regex;unit_test_framework;timer;chrono
-- Found Boost 1.70.0 at /usr/local/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET COMPONENTS system;program_options;regex;unit_test_framework;timer;chrono
-- Boost 1.65.1 found.
-- Found Boost components:
   system;program_options;regex;unit_test_framework;timer;chrono
-- Boost was not found.
-- Eigen3 3.3.4 was found at /usr/include/eigen3
-- Bliss is disabled
-- CLN is disabled
-- CoCoA is disabled
-- GiNaC is disabled
-- GTest 1.8.0 was found at /home/jianqiang/Downloads/carl-19.01/carl-19.01/build/resources/src/GTest-EP/googletest/include and /home/jianqiang/Downloads/carl-19.01/carl-19.01/build/resources/src/GTest-EP-build/googlemock/gtest/libgtest_main.a
-- Doxygen 1.8.13 was found at /usr/bin/doxygen
-- Found clang-tidy, use "make tidy" to run it.
-- Found clang-format, use "make format" to run it.
-- Could NOT find LATEX (missing: LATEX_COMPILER) 
-- Found PythonInterp: /usr/bin/python (found version "2.7.15") 
-- Registered with cmake
CMake Error at cmake/carlmacros.cmake:154 (get_target_property):
  get_target_property() called with non-existent target "Boost_SHARED".
Call Stack (most recent call first):
  cmake/export.cmake:41 (export_target_recursive)
  CMakeLists.txt:147 (include)

CMake Error at cmake/carlmacros.cmake:154 (get_target_property):
  get_target_property() called with non-existent target "Boost_STATIC".
Call Stack (most recent call first):
  cmake/export.cmake:42 (export_target_recursive)
  CMakeLists.txt:147 (include)

-- Run "make .travis.yml" to rebuild the travis file.
-- Configuring incomplete, errors occurred!
See also "/home/jianqiang/Downloads/carl-19.01/carl-19.01/build/CMakeFiles/CMakeOutput.log".

/--------------------------------------------------------------------------------------------------------
i've already installed the boost  and compiled by myself, but it seems that the script can not find it properly, and i've already tried install the libboost-all-dev, still can not resolve the issue
any suggestion would be helpful

**Comment by smtrat** [comment]
> libboost_system.so.1.70.0 (shared, BUILD_SHARED_LIBS not ON, set Boost_USE_STATIC_LIBS=OFF to override)

This looks like it only finds the shared version.
As of now, we try to provide both a shared and a static version and the graceful fallback if no static version is available is not well supported (sorry for that).
Could you build the static libs for boost as well and try again?

**Comment by Nervous-** [comment]
sorry，i just purged all the boost libraries installed and rebuild the carl, so  i can not reproduce the error now, but i agree with you, maybe you should refine related cmake scripts. for boost library finding, i think you should check the order of the boost finding related sentences, cause it turns out that several boost versions found during  configuration.
thank you for your helpful response, great work!
