### ISSUE TITLE
Does not compile with eigen3 on Ubuntu 16.10

### ISSUE THREAD

**Issue by sjunges** [smtrat/carl#3]
When trying to compile on ubuntu 16.10 with Eigen3 installed, carl does not compile:

[ 24%] Building CXX object src/carl/CMakeFiles/lib_carl.dir/formula/parser/OPBImporter.cpp.o
In file included from /usr/include/ginac/container.h:30:0,
                 from /usr/include/ginac/lst.h:26,
                 from /usr/include/ginac/normal.h:29,
                 from /usr/include/ginac/ginac.h:31,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/../../interval/../core/../converter/OldGinacConverter.h:20,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/../../interval/../core/MultivariateGCD.h:13,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/../../interval/../core/MultivariatePolynomial.h:1355,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/../../interval/../core/UnivariatePolynomial.h:38,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/../../interval/../core/FactorizedPolynomial.tpp:9,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/../../interval/../core/FactorizedPolynomial.h:1034,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/../../interval/IntervalEvaluation.h:15,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/../Constraint.h:23,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/../Formula.h:18,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/OPBImporter.h:3,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/OPBImporter.cpp:1:
/usr/include/eigen3/Eigen/src/Core/util/Constants.h:70:1: error: ‘deprecated’ was not declared in this scope
 EIGEN_DEPRECATED
 ^
/usr/include/eigen3/Eigen/src/Core/util/Constants.h:70:1: error: expected ‘)’ before ‘;’ token
 EIGEN_DEPRECATED
 ^
/usr/include/eigen3/Eigen/src/Core/util/Constants.h:70:1: error: expected ‘)’ before ‘;’ token
/usr/include/eigen3/Eigen/src/Core/util/Constants.h:70:1: error: declaration does not declare anything [-fpermissive]
In file included from /usr/include/eigen3/Eigen/Core:65:0,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/../model/mvroot/../../../core/rootfinder/../../formula/model/ran/../../../thom/SignDetermination/../TarskiQuery/CharPol.h:10,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/../model/mvroot/../../../core/rootfinder/../../formula/model/ran/../../../thom/SignDetermination/../TarskiQuery/MultivariateTarskiQuery.h:11,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/../model/mvroot/../../../core/rootfinder/../../formula/model/ran/../../../thom/SignDetermination/../TarskiQuery/TarskiQueryManager.h:13,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/../model/mvroot/../../../core/rootfinder/../../formula/model/ran/../../../thom/SignDetermination/SignDetermination.h:11,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/../model/mvroot/../../../core/rootfinder/../../formula/model/ran/../../../thom/ThomEncoding.h:10,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/../model/mvroot/../../../core/rootfinder/../../formula/model/ran/RealAlgebraicNumber.h:12,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/../model/mvroot/../../../core/rootfinder/RootFinder.h:12,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/../model/mvroot/MultivariateRoot.h:4,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/../VariableComparison.h:3,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/../Formula.h:23,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/OPBImporter.h:3,
                 from /home/sebastian/i2/carl/src/carl/formula/parser/OPBImporter.cpp:1:
/usr/include/eigen3/Eigen/src/Core/util/Constants.h:70:1: error: expected unqualified-id before ‘)’ token
 EIGEN_DEPRECATED
 ^
compilation terminated due to -fmax-errors=5.
src/carl/CMakeFiles/lib_carl.dir/build.make:446: recipe for target 'src/carl/CMakeFiles/lib_carl.dir/formula/parser/OPBImporter.cpp.o' failed
make[3]: *** [src/carl/CMakeFiles/lib_carl.dir/formula/parser/OPBImporter.cpp.o] Error 1
CMakeFiles/Makefile2:263: recipe for target 'src/carl/CMakeFiles/lib_carl.dir/all' failed
make[2]: *** [src/carl/CMakeFiles/lib_carl.dir/all] Error 2
CMakeFiles/Makefile2:1402: recipe for target 'bindings/pycarl/CMakeFiles/PythonBindingsDevelop.dir/rule' failed
make[1]: *** [bindings/pycarl/CMakeFiles/PythonBindingsDevelop.dir/rule] Error 2
Makefile:537: recipe for target 'PythonBindingsDevelop' failed
make: *** [PythonBindingsDevelop] Error 2

**Comment by smtrat** [comment]
Is this still an issue?
