### ISSUE TITLE
No rule to make target 'lib_carl'

### ISSUE THREAD

**Issue by oreohere** [smtrat/carl#31]
I'm trying to build carl on a docker container of ubuntu 19.04. I have all the necessary dependencies install so cmake works fine. However on trying to make libcarl, its says there's no rule. Need some immediate help. Was struggling to install in on mac as well.
<img width="1421" alt="Screen Shot 2019-09-18 at 6 48 01 PM" src="https://user-images.githubusercontent.com/14862450/65195423-de141480-da44-11e9-865c-ef42df41775b.png">

**Comment by oreohere** [comment]
A fresh install after deleting the folder did build carl without any error. I'm not sure why it happened though.

**Comment by nafur** [comment]
For the record and future questions: after quite some restructuring lib_carl as a target does no longer exist. Instead there are `carl-shared` and `carl-static`, as well as some others...

**Comment by oreohere** [comment]
I'm currently trying to build carl using master-14 branch (because storm suggests so). However, neither does make carl-shared nor does make carl-static work. Would making the whole carl (as in just make) provide all the needed libraries needed for storm and carl-parser?

**Comment by sjunges** [comment]
Storm depends on the master14 branch as carl in the master version uses features that many c++ compilers do not support. Its documentation regarding make lib_carl remains correct. 

For us, it remains a struggle to make a decision between using the current version of carl and supporting more than just brand-new compilers (that many operating systems do not ship with).
