### ISSUE TITLE
carl is unable to detect systems googletest

### ISSUE THREAD

**Issue by ForceFaction** [smtrat/carl#36]
Hi,

i'm trying to build carl with my systems googletest version. carl seems to be unable to find it. Also i could find a reference to find_package(GTest) or similar nowhere in the CMakeFiles, which suggests that it is not used or implicitly used. 

For the other dependencies carl first searches if the system has the libraries and only resorts to building it when they are not found. Why is this different for gtest?

ForceFaction

**Comment by nafur** [comment]
This goes back to the recommendation of gtest to not use system-wide installed libraries. The reasoning was that this could lead to undefined behaviour if the tests are not compiled with the exact same options as gtest itself, IIRC. This policy may have changed in the meantime, but it's unclear to me (see https://github.com/google/googletest/issues/902).
As gtest builds pretty quickly, I decided at the time to simply go with the recommendations and always build it with carl.

**Comment by ForceFaction** [comment]
Hm, you're right. After reading this thread it's also unclear to me, if it's officially discouraged or not. 

The reason why I'm bringing this up is: I'm currently trying to package Carl for the Guix package manager and the rule is that no bundled software shall be used when a system version of it is available or the bundled library could be of use as a single library.

Which bits (as in what files :D) should I change if I want to also be able to use a system gtest (and Google benchmark) installation?

**Comment by nafur** [comment]
Okay, so first you need to make cmake actually look for it. To do this change https://github.com/smtrat/carl/blob/master/resources/resources.cmake#L155 to something similar to https://github.com/smtrat/carl/blob/master/resources/resources.cmake#L82, like:
```
if(NOT FORCE_SHIPPED_RESOURCES)
	load_library(carl GTEST 0.0)
endif()
```

And then add a `FindGTEST.cmake`, probably based on `FindGMP.cmake` (https://github.com/smtrat/carl/blob/master/cmake/FindGMP.cmake). It first looks for the include dir (replace `gmp.h` by `gtest.h`), then the library (replace `gmp` by `gtest`), then parses the version information (regex on the header, but can be skipped). Also change all variable names from `GMP_` to `GTEST_`.
This may be sufficient... probably something subtle will fail, though...

**Comment by ForceFaction** [comment]
Thanks for those pointers! I'll give it a try this weekend :)

**Comment by ForceFaction** [comment]
So i tried it out and CMake seems to come bundled with a FindGTest.cmake.

This makes carl use the system version. I didn't try to make it possible to retain old behaviour if GTest isn't found in the system.

[0001-testing-system-cmake-configuration.txt](https://github.com/smtrat/carl/files/5446640/0001-testing-system-cmake-configuration.txt)
