### ISSUE TITLE
Build fails: latest libcarl, boost 1.74

### ISSUE THREAD

**Issue by huypn12** [smtrat/carl#39]
System: Opensuse Tumbleweed
CC: GCC 10.2.1
```
$ mkdir build
$ cd build
$ cmake  -DUSE_CLN_NUMBERS=ON -DUSE_GINAC=ON -DTHREAD_SAFE=ON .. # cln-devel and ginac-devel installed
$ make
```
The following error appears, says "no rule to make  lib_shared-NOTFOUND"

![grafik](https://user-images.githubusercontent.com/2792821/100530080-d544d400-31ed-11eb-8755-a38c240a8d49.png)

**Comment by volkm** [comment]
Which carl branch are you using, `master` or `master14`? If you want to build carl for use with Storm, you should switch to the `master14` branch.

**Comment by huypn12** [comment]
the reason here is that i am building storm in my linux box with libboost version 1.74, shared lib. However, during the build progress carl sticks to libboost 1.64 and later it claims that it finds no libboost_...1.64
I think this can be solved quite easily by forcing storm to use static, manually built libboost 1.64. But I just wondered that latest version of carl can use my system boost.

**Comment by huypn12** [comment]
I have a question: Why do you stick to fixed version 1.58 and 1.64 of boost here? And how can I build carl using the boost installed in my system?

![grafik](https://user-images.githubusercontent.com/2792821/100909405-f9920080-34cc-11eb-925e-388f2265d9da.png)

**Comment by huypn12** [comment]
I added this line to resources/resources.cmake
Now carl (also storm :) ) built and works on my system with libboost 1.74 shared lib

![grafik](https://user-images.githubusercontent.com/2792821/100931578-01609d80-34eb-11eb-80e9-b15737293bc3.png)

**Comment by nafur** [comment]
As @volkm asked, you are probably on master14. This is a pretty old version of carl (14 as in 2014!) and thus expects an old version of boost. While a new version might just work (and seems to work in your case), going to a newer boost version has had issues many times in the past, and thus carl does not just take whatever boost version it finds.
As it works for you, I close this issue.
