### ISSUE TITLE
Release make doc fails

### ISSUE THREAD

**Issue by matu3ba** [smtrat/carl#5]
Is this a known issue?
It is unfortunate to have no documentation for the build.
`mkdir build && cd build && cmake ../
make
make test
make install`
works, though
`make doc`fails.
Having something like
error: /home/user/BachelorArbeit/carl/carl-17.02/src/carl/io/../core/../numbers/adaption_gmpxx/../typetraits.h:200:20: error: use of undeclared identifier 'std' [clang]
or
error: /home/user/BachelorArbeit/carl/carl-17.02/src/carl/converter/../numbers/adaption_float/../../util/SFINAE.h:89:1: error: use of undeclared identifier 'std' [clang]
or multiple
error: /usr/include/wchar.h:39:11: fatal error: 'stdarg.h' file not found [clang]
I stopped after some minutes of only errors.
Any specific version of gmp or package needed in
https://smtrat.github.io/carl/dependencies.html ?
git, cmake, g++, clang, doxygen, gtest (google test bench), libeigen3-dev, boost installed by packages on Ubuntu 16.04 LTS,
gmp 6.2.1 installed, make resources also not complaining.

**Comment by smtrat** [comment]
Fixed as of d960e60 (I hope).
I tried to use clang-assisted parsing at some point and it never got removed as our docs are built with an old doxygen version that ignores this flag...
