### ISSUE TITLE
No arch package build file

### ISSUE THREAD

**Issue by WorldSEnder** [smtrat/carl#9]
Currently the library is not part of the community packages for arch. I have attached a build file that I currently use on my local machine. Feel free to adapt and use it for bring the library to the community repositories for arch.

https://gist.github.com/WorldSEnder/76385c2b2657752b7bbe12f24d89df67

**Comment by nafur** [comment]
Thanks for the input. I always wanted to do that, but never actually did.

Could you check whether it works? (-> https://aur.archlinux.org/packages/carl/ )

**Comment by WorldSEnder** [comment]
It currently does not work.

First replace

source=("$pkgname::git+https://github.com/smtrat/carl.git#17.04")

with 

source=("$pkgname::git+https://github.com/smtrat/carl.git#tag=17.04")

Furthermore, the tests are currently not run, and that is reported as an error during installation. The reason is that they are never built, thus not found and then not run. It works when I modify

check() {
  cd "$pkgname"
  make // Can probably be more specific
  make test
}

**Comment by nafur** [comment]
I figured I could simply install it on my machine (also using arch) although I use a local clone of carl, and then noticed the same issues as you described.
They should now be fixed: https://aur.archlinux.org/cgit/aur.git/log/?h=carl
It now successfully builds, runs the tests and installs (on my machine)
However, the install target still installs some unnecessary stuff...

**Comment by WorldSEnder** [comment]
Works fine for me, I think we can close this issue
